# -*- coding: utf-8 -*-
"""sentiment analysis ( project )

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tln9yBXFQ8WEJa6LeVddmY8ADiMXNEm5

# STEP 1 - Loading the Dataset

Load the Dataset
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Step 1: Load the dataset into the drive. Check the correct dataset file name.
file_name = "/content/final_dataset_sentiment analysis.xlsx"  # Replace with the correct name if different
data = pd.read_excel(file_name)

# Step 2: Display the first few rows of the dataset
print(data.head())

"""Understand the Dataset Structure"""

# Assuming the dataset has already been loaded into the 'data' DataFrame
print("Column names in the dataset:")
print(data.columns.tolist())

"""# Step 2 - Data Cleaning"""

# 1. Check for null values in each column
print("Null values in each column:\n", data.isnull().sum())

# 2. Check for duplicate rows
print("\nDuplicate rows count:", data.duplicated().sum())

# 3. Remove duplicate rows
data = data.drop_duplicates()

# 4. Verify cleaning
print("\nAfter cleaning:")
print("Null values in each column:\n", data.isnull().sum())
print("Duplicate rows count:", data.duplicated().sum())

# 5. Show the updated shape of the dataset
print("\nFinal dataset shape:", data.shape)

import seaborn as sns
import matplotlib.pyplot as plt

# Step 1: Clean labels (lowercase, strip spaces)
data['REACTION'] = data['REACTION'].str.strip().str.lower()

# Step 2: Keep only correct sentiment labels
correct_labels = ['positive', 'negative', 'neutral']
data = data[data['REACTION'].isin(correct_labels)]

# Step 3: Recheck value counts (optional)
print("Label counts after cleaning:\n", data['REACTION'].value_counts())

# Step 4: Plot cleaned sentiment distribution
plt.figure(figsize=(3, 3))
sns.countplot(x='REACTION', data=data, palette='Set2')
plt.title('Distribution of Sentiment Labels')
plt.xlabel('Sentiment')
plt.ylabel('Count')
plt.show()

"""# Step - 3 Data Preprocessing"""

# Install the emoji library
!pip install emoji --quiet

# Install the emoji library
!pip install emoji --quiet

import nltk #nltk is a library for natural language processing
import string # string is a module for working with strings
import emoji # emoji is a library for working with emojis
import re # re is a module for working with regular expressions
from nltk.corpus import stopwords # stopwords is a module for working with stopwords
from nltk.tokenize import word_tokenize # word_tokenize is a function for tokenizing text into words

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab') # Add this line to download the missing resource


stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    text = emoji.demojize(text, language='en')                     # Convert emojis to text
    text = text.lower()                                            # Lowercase
    text = re.sub(r'\d+', '', text)                                # Remove numbers
    text = re.sub(r':\w+:', '', text)                              # Remove emoji text like :smile:
    text = text.translate(str.maketrans('', '', string.punctuation))  # Remove punctuation
    text = re.sub(r'\s+', ' ', text).strip()                       # Normalize whitespace
    tokens = word_tokenize(text)                                   # Tokenize
    tokens = [word for word in tokens if word not in stop_words]   # Remove stopwords
    return ' '.join(tokens)

data['clean_text'] = data['TEXT'].apply(preprocess_text)

# Install emoji library if not already installed
!pip install emoji --quiet

import nltk
import string
import emoji
from nltk.corpus import stopwords

# Download stopwords
nltk.download('stopwords')

# Define English stopwords
stop_words = set(stopwords.words('english'))

# Step 1: Convert emojis to text
def convert_emojis(text):
    return emoji.demojize(text, language='en')

# Step 2: Full preprocessing function
def preprocess_text(text):
    text = convert_emojis(text)  # Convert emojis to text
    text = text.lower()  # Lowercase
    text = ''.join(char for char in text if char not in string.punctuation)  # Remove punctuation
    tokens = text.split()  # Tokenize
    tokens = [word for word in tokens if word not in stop_words]  # Remove stopwords
    return ' '.join(tokens)

# Apply preprocessing
data['clean_text'] = data['TEXT'].apply(preprocess_text)

# View sample cleaned messages
print(data[['TEXT', 'clean_text']].head())

"""# Step - 4 model training"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

# Step 1: Vectorize the clean text using TF-IDF
vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1, 2))
X = vectorizer.fit_transform(data['clean_text'])

# Step 2: Prepare labels
y = data['REACTION']

# Step 3: Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# Step 4: Train Naive Bayes classifier
model = MultinomialNB()
model.fit(X_train, y_train)

# Step 5: Predict and evaluate
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm = confusion_matrix(y_test, y_pred, labels=['positive', 'negative', 'neutral'])
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['positive', 'negative', 'neutral'])
disp.plot(cmap='Blues')  # Better color map
plt.title('Confusion Matrix')
plt.show()

from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc
from sklearn.multiclass import OneVsRestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
import matplotlib.pyplot as plt
from sklearn.metrics import RocCurveDisplay
import numpy as np

# Step 1: Binarize the target labels for multi-class ROC
classes = ['positive', 'neutral', 'negative']
y_binarized = label_binarize(data['REACTION'], classes=classes)

# Step 2: Vectorize the text
vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1, 2))
X = vectorizer.fit_transform(data['clean_text'])

# Step 3: Train/Test split
X_train, X_test, y_train_bin, y_test_bin = train_test_split(
    X, y_binarized, test_size=0.2, random_state=42, stratify=y_binarized
)

# Step 4: Train One-vs-Rest classifier
classifier = OneVsRestClassifier(MultinomialNB())
classifier.fit(X_train, y_train_bin)
y_score = classifier.predict_proba(X_test)

# Step 5: Plot ROC Curve
fpr = {}
tpr = {}
roc_auc = {}

for i in range(len(classes)):
    fpr[i], tpr[i], _ = roc_curve(y_test_bin[:, i], y_score[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

plt.figure(figsize=(6, 5))
for i, label in enumerate(classes):
    plt.plot(fpr[i], tpr[i], label=f'{label} (AUC = {roc_auc[i]:.2f})')

plt.plot([0, 1], [0, 1], 'k--')  # Diagonal line
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve - Multi-class Sentiment Classification')
plt.legend(loc='lower right')
plt.grid()
plt.tight_layout()
plt.show()

!pip show emoji

# Function to preprocess a single sentence (same as training preprocessing)
def preprocess_input(text):
    text = emoji.demojize(text, language='en')  # Convert emojis to text
    text = text.lower()  # Lowercase
    text = ''.join(char for char in text if char not in string.punctuation)  # Remove punctuation
    tokens = text.split()  # Tokenize
    tokens = [word for word in tokens if word not in stop_words]  # Remove stopwords
    return ' '.join(tokens)

# User input loop
while True:
    user_text = input("\nEnter a sentence (or type 'exit' to quit): ")
    if user_text.lower() == 'exit':
        print("Goodbye! 👋")
        break

    # Preprocess and vectorize
    clean_text = preprocess_input(user_text)
    vectorized_text = vectorizer.transform([clean_text])

    # Predict sentiment
    prediction = model.predict(vectorized_text)[0]

    print(f"Predicted Sentiment: {prediction.capitalize()}")





